projects:
  Todo App:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: pomr6f7mmfgxfkz3cpaels5nde
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        maxDepth: 2
      endpoints:
        prod: >-
          https://mxdj2unuejdbvlaljslriyqkgq.appsync-api.eu-central-1.amazonaws.com/graphql
